import { useState, useEffect } from 'react'

const STATUS_COLORS = {
  filed: 'bg-red-100 text-red-800',
  acknowledged: 'bg-yellow-100 text-yellow-800',
  resolved: 'bg-green-100 text-green-800',
  rejected: 'bg-gray-100 text-gray-800',
}

const SEVERITY_COLORS = {
  low: 'bg-blue-100 text-blue-800',
  medium: 'bg-yellow-100 text-yellow-800',
  high: 'bg-orange-100 text-orange-800',
  critical: 'bg-red-100 text-red-800',
}

const INCIDENT_ICONS = {
  theft: '📱', robbery: '💰', assault: '👊', sexual_harassment: '🚨',
  accident: '🚂', falling: '⬇️', death: '💀', platform_gap: '⚠️',
  overcrowding: '👥', delay: '🕐', nuisance: '🔊', chain_pulling: '⛓️',
  corruption: '💸', staff_misconduct: '👤', infrastructure: '🏗️',
  stampede: '🏃', general: '📋',
}

/**
 * Open a print-ready window with the FIR/complaint formatted as a proper police document.
 */
function downloadComplaintPDF(complaint) {
  const w = window.open('', '_blank', 'width=800,height=1000')
  if (!w) return alert('Please allow popups to download the PDF')

  const isGRPFIR = complaint.complaint_text?.includes('FIRST INFORMATION REPORT')
    || complaint.complaint_text?.includes('प्रथम सूचना रिपोर्ट')
    || complaint.complaint_text?.includes('प्रथम खबरी अहवाल')
  const isCPGRAMS = complaint.complaint_text?.includes('CPGRAMS')
    || complaint.complaint_text?.includes('सीपीजीआरएएमएस')
  const isRCT = complaint.complaint_text?.includes('RAILWAY CLAIMS TRIBUNAL')
    || complaint.complaint_text?.includes('रेलवे दावा अधिकरण')
    || complaint.complaint_text?.includes('रेल्वे दावे न्यायाधिकरण')

  let docTitle = 'Complaint Document'
  if (isGRPFIR) docTitle = 'First Information Report (FIR)'
  else if (isCPGRAMS) docTitle = 'CPGRAMS Grievance Form'
  else if (isRCT) docTitle = 'RCT Compensation Application'

  let htmlBody = complaint.complaint_text || 'No complaint text available'
  htmlBody = htmlBody.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  htmlBody = `<pre style="font-family: 'Courier New', monospace; font-size: 12px; line-height: 1.6; white-space: pre-wrap; word-wrap: break-word;">${htmlBody}</pre>`

  w.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${docTitle} — ${complaint.ref}</title>
  <style>
    @page { margin: 20mm 15mm; size: A4; }
    body {
      font-family: 'Courier New', 'Noto Sans Devanagari', monospace;
      margin: 0; padding: 20px;
      color: #000;
    }
    .header {
      text-align: center; border-bottom: 2px solid #000;
      padding-bottom: 10px; margin-bottom: 15px;
    }
    .header h2 { margin: 0; font-size: 16px; }
    .header .ref { font-size: 11px; color: #555; margin-top: 4px; }
    .meta { font-size: 11px; color: #333; margin-bottom: 15px;
      display: flex; justify-content: space-between; }
    .doc-body pre {
      font-family: 'Courier New', 'Noto Sans Devanagari', monospace;
      font-size: 12px; line-height: 1.6;
      white-space: pre-wrap; word-wrap: break-word;
    }
    .footer {
      margin-top: 20px; padding-top: 10px; border-top: 1px solid #ccc;
      font-size: 10px; color: #777; text-align: center;
    }
    .no-print { margin: 20px 0; text-align: center; }
    .no-print button {
      padding: 10px 30px; font-size: 14px; cursor: pointer;
      background: #1e3a5f; color: white; border: none;
      border-radius: 6px; margin: 0 5px;
    }
    .no-print button:hover { background: #2a4f7f; }
    @media print { .no-print { display: none; } }
  </style>
</head>
<body>
  <div class="no-print">
    <button onclick="window.print()">Print / Save as PDF</button>
    <button onclick="window.close()">Close</button>
  </div>
  <div class="header">
    <h2>${docTitle}</h2>
    <div class="ref">Reference: ${complaint.ref} | Status: ${(complaint.status || '').toUpperCase()}</div>
  </div>
  <div class="meta">
    <span>Complainant: ${complaint.user_name || 'N/A'}</span>
    <span>Incident: ${(complaint.incident_type || '').replace('_', ' ').toUpperCase()}</span>
    <span>Severity: ${(complaint.severity || '').toUpperCase()}</span>
  </div>
  <div class="doc-body">${htmlBody}</div>
  <div class="footer">
    Generated by Jan Suraksha Bot — RailFLOW Platform | ${new Date().toLocaleString('en-IN')}
  </div>
</body>
</html>`)
  w.document.close()
}

export default function PoliceDashboard() {
  const [complaints, setComplaints] = useState([])
  const [loading, setLoading] = useState(false)
  const [statusFilter, setStatusFilter] = useState('')
  const [typeFilter, setTypeFilter] = useState('')
  const [actionLoading, setActionLoading] = useState(null)

  // Modal state for resolve/reject notes
  const [modal, setModal] = useState(null) // { ref, action, note }

  const fetchComplaints = async () => {
    setLoading(true)
    try {
      const params = new URLSearchParams()
      if (statusFilter) params.set('status', statusFilter)
      if (typeFilter) params.set('type', typeFilter)
      const url = `/api/complaints/${params.toString() ? '?' + params.toString() : ''}`
      const res = await fetch(url)
      const data = await res.json()
      setComplaints(data.complaints || [])
    } catch {
      setComplaints([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchComplaints() }, [statusFilter, typeFilter])

  const updateStatus = async (ref, status, note = '') => {
    setActionLoading(ref)
    try {
      const res = await fetch(`/api/complaints/${ref}/status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status, note }),
      })
      if (res.ok) {
        fetchComplaints()
        setModal(null)
      }
    } catch { /* noop */ } finally {
      setActionLoading(null)
    }
  }

  const openModal = (ref, action) => {
    setModal({ ref, action, note: '' })
  }

  // Stats
  const stats = {
    filed: complaints.filter(c => c.status === 'filed').length,
    acknowledged: complaints.filter(c => c.status === 'acknowledged').length,
    resolved: complaints.filter(c => c.status === 'resolved').length,
    rejected: complaints.filter(c => c.status === 'rejected').length,
  }
  const total = complaints.length

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
      {/* Left: Filters + Stats */}
      <div className="space-y-4">
        {/* Stats */}
        <div className="bg-white rounded-xl shadow-sm p-4">
          <div className="font-semibold text-sm mb-3">Complaint Stats</div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs text-gray-600">Total</span>
              <span className="text-lg font-bold text-[#1e3a5f]">{total}</span>
            </div>
            <div className="h-px bg-gray-100" />
            {Object.entries(stats).map(([status, count]) => (
              <div key={status} className="flex items-center justify-between">
                <span className={`px-2 py-0.5 rounded-full text-[10px] font-medium ${STATUS_COLORS[status]}`}>
                  {status.toUpperCase()}
                </span>
                <span className="text-sm font-semibold">{count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Filters */}
        <div className="bg-white rounded-xl shadow-sm p-4">
          <div className="font-semibold text-sm mb-3">Filters</div>
          <div className="space-y-3">
            <div>
              <label className="block text-xs font-medium text-gray-500 mb-1">Status</label>
              <select
                value={statusFilter}
                onChange={e => setStatusFilter(e.target.value)}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm bg-gray-50"
              >
                <option value="">All</option>
                <option value="filed">Filed</option>
                <option value="acknowledged">Acknowledged</option>
                <option value="resolved">Resolved</option>
                <option value="rejected">Rejected</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-500 mb-1">Incident Type</label>
              <select
                value={typeFilter}
                onChange={e => setTypeFilter(e.target.value)}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm bg-gray-50"
              >
                <option value="">All</option>
                {Object.keys(INCIDENT_ICONS).map(t => (
                  <option key={t} value={t}>{t.replace('_', ' ')}</option>
                ))}
              </select>
            </div>
          </div>
        </div>

        {/* Refresh */}
        <button
          onClick={fetchComplaints}
          className="w-full bg-[#1e3a5f] text-white py-2 rounded-lg text-sm font-medium hover:bg-[#2a4f7f]"
        >
          Refresh
        </button>
      </div>

      {/* Right: Ticket Cards */}
      <div className="lg:col-span-3 space-y-3">
        <div className="bg-white rounded-xl shadow-sm px-5 py-3 border-b border-gray-100">
          <div className="font-semibold text-sm">Police Dashboard — Jan Suraksha Complaint Management</div>
          <div className="text-[10px] text-gray-400">Complaint tickets filed by railway passengers via Jan Suraksha Bot</div>
        </div>

        {loading && <div className="text-center text-gray-400 py-8 text-sm">Loading complaints...</div>}

        {!loading && complaints.length === 0 && (
          <div className="text-center text-gray-400 py-12 bg-white rounded-xl shadow-sm">
            <div className="text-3xl mb-2">📋</div>
            <div className="text-sm font-medium">No complaints found</div>
            <div className="text-xs mt-1">Complaints filed via Jan Suraksha Bot will appear here</div>
          </div>
        )}

        {complaints.map(c => (
          <div key={c.ref} className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
            {/* Ticket Header */}
            <div className="px-5 py-3 flex items-start justify-between">
              <div className="flex items-start gap-3">
                <div className="text-2xl">{INCIDENT_ICONS[c.incident_type] || '📋'}</div>
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-mono text-xs text-gray-500">{c.ref}</span>
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-medium ${STATUS_COLORS[c.status] || ''}`}>
                      {c.status?.toUpperCase()}
                    </span>
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-medium ${SEVERITY_COLORS[c.severity] || ''}`}>
                      {c.severity?.toUpperCase()}
                    </span>
                  </div>
                  <div className="text-sm font-semibold text-[#1e3a5f]">
                    {c.incident_type?.replace('_', ' ').toUpperCase()}
                  </div>
                  <div className="text-xs text-gray-500 mt-0.5">
                    User: {c.user_name || 'Unknown'} | Authority: {c.authority || 'N/A'}
                  </div>
                </div>
              </div>
              <div className="text-right">
                <div className="text-[10px] text-gray-400">
                  {c.date_filed ? new Date(c.date_filed).toLocaleDateString('en-IN', {
                    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
                  }) : ''}
                </div>
              </div>
            </div>

            {/* User Message */}
            <div className="px-5 pb-2">
              <div className="bg-gray-50 rounded-lg px-3 py-2 text-sm text-gray-700 italic">
                "{c.user_message || 'No message'}"
              </div>
            </div>

            {/* Officer Note (if exists) */}
            {c.officer_note && (
              <div className="px-5 pb-2">
                <div className="bg-blue-50 rounded-lg px-3 py-2 text-xs text-blue-700">
                  Officer note: {c.officer_note}
                </div>
              </div>
            )}

            {/* Expandable Complaint Text + Download */}
            {c.complaint_text && (
              <div className="px-5 pb-2 space-y-2">
                <details className="bg-gray-50 rounded-lg border border-gray-200">
                  <summary className="px-3 py-2 text-xs font-semibold text-gray-600 cursor-pointer hover:bg-gray-100">
                    View Complaint Draft
                  </summary>
                  <div className="px-3 py-2 text-xs whitespace-pre-wrap border-t border-gray-100 bg-white max-h-60 overflow-y-auto font-mono">
                    {c.complaint_text}
                  </div>
                </details>
                <button
                  onClick={() => downloadComplaintPDF(c)}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-[#1e3a5f] text-white rounded-lg text-xs font-medium hover:bg-[#2a4f7f]"
                >
                  Download FIR / Complaint PDF
                </button>
              </div>
            )}

            {/* Action Buttons — filed status */}
            {c.status === 'filed' && (
              <div className="px-5 py-3 bg-gray-50 border-t border-gray-100 flex items-center gap-2">
                <button
                  onClick={() => updateStatus(c.ref, 'acknowledged')}
                  disabled={actionLoading === c.ref}
                  className="px-4 py-1.5 bg-yellow-500 text-white rounded-lg text-xs font-medium hover:bg-yellow-600 disabled:opacity-50"
                >
                  Acknowledge
                </button>
                <button
                  onClick={() => openModal(c.ref, 'resolved')}
                  disabled={actionLoading === c.ref}
                  className="px-4 py-1.5 bg-green-600 text-white rounded-lg text-xs font-medium hover:bg-green-700 disabled:opacity-50"
                >
                  Resolve
                </button>
                <button
                  onClick={() => openModal(c.ref, 'rejected')}
                  disabled={actionLoading === c.ref}
                  className="px-4 py-1.5 bg-red-500 text-white rounded-lg text-xs font-medium hover:bg-red-600 disabled:opacity-50"
                >
                  Reject
                </button>
              </div>
            )}

            {/* Action Buttons — acknowledged status */}
            {c.status === 'acknowledged' && (
              <div className="px-5 py-3 bg-gray-50 border-t border-gray-100 flex items-center gap-2">
                <button
                  onClick={() => openModal(c.ref, 'resolved')}
                  disabled={actionLoading === c.ref}
                  className="px-4 py-1.5 bg-green-600 text-white rounded-lg text-xs font-medium hover:bg-green-700 disabled:opacity-50"
                >
                  Resolve
                </button>
                <button
                  onClick={() => openModal(c.ref, 'rejected')}
                  disabled={actionLoading === c.ref}
                  className="px-4 py-1.5 bg-red-500 text-white rounded-lg text-xs font-medium hover:bg-red-600 disabled:opacity-50"
                >
                  Reject
                </button>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Modal Overlay for Resolve/Reject Notes */}
      {modal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md">
            <div className="px-6 py-4 border-b border-gray-100">
              <div className="font-semibold text-sm text-[#1e3a5f]">
                {modal.action === 'resolved' ? 'Resolve Complaint' : 'Reject Complaint'}
              </div>
              <div className="text-xs text-gray-400 mt-0.5">
                Ref: {modal.ref}
              </div>
            </div>

            <div className="px-6 py-4">
              <label className="block text-xs font-medium text-gray-600 mb-2">
                {modal.action === 'resolved'
                  ? 'Resolution note (optional)'
                  : 'Reason for rejection (required)'}
              </label>
              <textarea
                value={modal.note}
                onChange={e => setModal({ ...modal, note: e.target.value })}
                rows={3}
                placeholder={modal.action === 'resolved'
                  ? 'e.g. Phone recovered from suspect at Dadar station'
                  : 'e.g. Insufficient evidence to proceed'}
                className="w-full border border-gray-200 rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-[#ff6b35] focus:ring-1 focus:ring-[#ff6b35] resize-none"
                autoFocus
              />
            </div>

            <div className="px-6 py-3 bg-gray-50 rounded-b-2xl flex items-center justify-end gap-2">
              <button
                onClick={() => setModal(null)}
                className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800 font-medium"
              >
                Cancel
              </button>
              <button
                onClick={() => {
                  if (modal.action === 'rejected' && !modal.note.trim()) return
                  updateStatus(modal.ref, modal.action, modal.note)
                }}
                disabled={modal.action === 'rejected' && !modal.note.trim()}
                className={`px-5 py-2 rounded-xl text-sm font-medium text-white transition-colors disabled:opacity-50 disabled:cursor-not-allowed ${
                  modal.action === 'resolved'
                    ? 'bg-green-600 hover:bg-green-700'
                    : 'bg-red-500 hover:bg-red-600'
                }`}
              >
                {modal.action === 'resolved' ? 'Resolve' : 'Reject'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}